INSERT INTO VEHICLE (VEHICLE_TYPE, VEHICLE_MODEL, NUMBER_OF_PASSENGERS, NUMBER_OF_KILOMETERS, PRODUCTION_YEAR) VALUES ("Audi", "RS5", "5", "35_000", "2018");
INSERT INTO VEHICLE (VEHICLE_TYPE, VEHICLE_MODEL, NUMBER_OF_PASSENGERS, NUMBER_OF_KILOMETERS, PRODUCTION_YEAR) VALUES ("Audi", "TTRS", "2", "25_000", "2017");
INSERT INTO VEHICLE (VEHICLE_TYPE, VEHICLE_MODEL, NUMBER_OF_PASSENGERS, NUMBER_OF_KILOMETERS, PRODUCTION_YEAR) VALUES ("Lexus", "RCF", "4", "23_000", "2018");
INSERT INTO VEHICLE (VEHICLE_TYPE, VEHICLE_MODEL, NUMBER_OF_PASSENGERS, NUMBER_OF_KILOMETERS, PRODUCTION_YEAR) VALUES ("Mazda", "MX5", "2", "45_000", "2015");
INSERT INTO VEHICLE (VEHICLE_TYPE, VEHICLE_MODEL, NUMBER_OF_PASSENGERS, NUMBER_OF_KILOMETERS, PRODUCTION_YEAR) VALUES ("Subaru", "Ascent", "8", "30_000", "2019");
INSERT INTO VEHICLE (VEHICLE_TYPE, VEHICLE_MODEL, NUMBER_OF_PASSENGERS, NUMBER_OF_KILOMETERS, PRODUCTION_YEAR) VALUES ("Alfa Romeo", "4C", "2", "15_000", "2018");

INSERT INTO CLIENT (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES ("Harry", "McMann", "har@b.c", "United States", "84 Beacon Street, Boston", "MA", "valid phone1");
INSERT INTO CLIENT (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES ("Doc", "Brown", "doc@b.c", "United States", "1640 Riverside Drive, Hill Valley", "CA", "valid phone2");
INSERT INTO CLIENT (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES ("Timothy", "Taylor", "power@b.c", "United States", "510 Glenview, Detroit", "MI", "valid phone3");
INSERT INTO CLIENT (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES ("Gomez", "Addams", "suave@b.c", "United States", "1313 Cemetery Lane, Augusta", "ME", "valid phone4");
INSERT INTO CLIENT (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES ("Phoebe", "Buffay", "Therapy@b.c", "United States", "5 Morton St. Apt. 14. NYC", "NY", "valid phone5");

INSERT INTO RESERVATION (VEHICLE_ID, RESERVATION_DATE) VALUES ((SELECT VEHICLE_ID FROM VEHICLE_MODEL = "RS5"), (SELECT CLIENT_ID FROM CLIENT WHERE LAST_NAME = "McMann"), "9/29/2020");